version: '3'
services:
  mydb:
    image: stackupiss/northwind-db:v1
    networks:
      - myapp-net
    volumes:
      - mydb-vol:/var/lib/mysql

  myapp:
    image: stackupiss/northwind-app:v1
    environment:
      - PORT=3000
      - DB_HOST=mydb
      - DB_USER=root
      - DB_PASSWORD=changeit
    ports:
      - 8080:3000
    networks:
      - myapp-net

volumes:
  mydb-vol:

networks:
  myapp-net:
