---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  namespace: csns
  labels:
    app: code-server
    name: cs-svc
spec:
  accessModes:
    - ReadWriteOnce
  # accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-xfs
---
# k get sc