---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: bggapp-po  # match template label
  template: # refers to pod template
    metadata:
      name: bggapp-po
      labels: 
        name: bggapp-po
    spec: 
      containers: 
      - name: app-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        envFrom: 
        - configMapRef:
            name: bgg-cm
        - secretRef: 
            name: bgg-secret 
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
  namespace: bggns
spec:
  type: NodePort
  selector:
      name: bggapp-po    
  ports: 
  - port: 80
    targetPort: 3000
---
