---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bggdb-deploy
  labels:
    name: bggdb-deploy
  namespace: bggns
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
        name: bggdb-po
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 3306 # container exposed port
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels: 
    name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    name: bggdb-po  # match template label 
  ports:
  - port: 3306 # service port for external to hit
    targetPort: 3306 # container port for service to hit
--- 
